### ISSUE TITLE
don't import the header  "NSDictionary+SafeKit.h"

### ISSUE THREAD

**Issue by WhisperRain** [JJMM/SafeKit#10]
Hello manager 
         In the path "SafeKit/SafeKit/Foundation/Foundation+SafeKit.h",  I noticed that you don't import the header of "NSDictionary+SafeKit.h".   Did you forget this  header file or  I just mistaken?  Please let me know the answer.

**Comment by JJMM** [comment]
Yes, I forgot the header, but it didn't affect the function.
