### ISSUE TITLE
您好！能否告诉我哪些核心代码是防止crash，让app继续运行的呢？

### ISSUE THREAD

**Issue by xhzengAIB** [JJMM/SafeKit#4]
@JJMM 

我看了一下您的结构，大概看到你用分类来做Foundation框架的基本类型的一些常用方法做防止，但是对于其他不crash的处理的核心代码在哪里呢？

Jack

**Comment by xunan623** [comment]
我的项目用了这个库之后,数组字典不会崩溃了,但是还会出现其他的崩溃...有更多方面的封装吗

**Comment by yhryyq** [comment]
您好


这个问题您为什么会问我啊 :)


您是在哪看到我的相关回复了么？




On 11/23/2015 12:05, xunan623 wrote:

我的项目用了这个库之后,数组字典不会崩溃了,但是还会出现其他的崩溃...有更多方面的封装吗

**Comment by JJMM** [comment]
可以看源码，被swizzle的方法不会crash，处理常用的方法和字面量，不常用的暂时没有处理
如野指针等OC系统问题还是会crash的






在 2015-11-23 12:05:23，"xunan623" <notifications@github.com> 写道：


我的项目用了这个库之后,数组字典不会崩溃了,但是还会出现其他的崩溃...有更多方面的封装吗
