### ISSUE TITLE
添加进项目运行就崩溃

### ISSUE THREAD

**Issue by taidypanda** [JJMM/SafeKit#9]
- (id)SKperformSelector:(SEL)aSelector{
    if ([self respondsToSelector:aSelector]) {
        if (getSafeKitObjectPerformExceptionCatch() == SafeKitObjectPerformExceptionCatchOn) {
            if ([self isSelectorReturnType:aSelector]) {
                typedef id (*MethodType)(id, SEL);
                MethodType methodToCall = (MethodType)[self methodForSelector:aSelector];
                return methodToCall(self, aSelector);
            }else{
                typedef void (*MethodType)(id, SEL);
                MethodType methodToCall = (MethodType)[self methodForSelector:aSelector];
                methodToCall(self, aSelector);
                return nil;
            }
        }else{
            if ([self isSelectorReturnType:aSelector]) {
                typedef id (*MethodType)(id, SEL);
                MethodType methodToCall = (MethodType)[self methodForSelector:aSelector];
                return methodToCall(self, aSelector);
            }else{
                typedef void (*MethodType)(id, SEL);
                MethodType methodToCall = (MethodType)[self methodForSelector:aSelector];
                methodToCall(self, aSelector);
                return nil;
            }
        }
    }else{
        [[SafeKitLog shareInstance]logError:[NSString stringWithFormat:@"[%@ %@] unrecognized selector sent to instance ",[[self class]description],NSStringFromSelector(aSelector)]];
    }
    return nil;
}
一运行就崩到           
     return methodToCall(self, aSelector);
这一行

**Comment by JJMM** [comment]
已经去掉SKperformSelector的swizzle
